package sample.domain.model;

import java.util.ArrayList;
import java.util.List;

public class QManageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public QManageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Short value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Short value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Short value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Short value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Short value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Short value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Short> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Short> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Short value1, Short value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Short value1, Short value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdIsNull() {
            addCriterion("q_category_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdIsNotNull() {
            addCriterion("q_category_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdEqualTo(Short value) {
            addCriterion("q_category_parent_id =", value, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdNotEqualTo(Short value) {
            addCriterion("q_category_parent_id <>", value, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdGreaterThan(Short value) {
            addCriterion("q_category_parent_id >", value, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdGreaterThanOrEqualTo(Short value) {
            addCriterion("q_category_parent_id >=", value, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdLessThan(Short value) {
            addCriterion("q_category_parent_id <", value, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdLessThanOrEqualTo(Short value) {
            addCriterion("q_category_parent_id <=", value, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdIn(List<Short> values) {
            addCriterion("q_category_parent_id in", values, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdNotIn(List<Short> values) {
            addCriterion("q_category_parent_id not in", values, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdBetween(Short value1, Short value2) {
            addCriterion("q_category_parent_id between", value1, value2, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryParentIdNotBetween(Short value1, Short value2) {
            addCriterion("q_category_parent_id not between", value1, value2, "qCategoryParentId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdIsNull() {
            addCriterion("q_category_child_id is null");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdIsNotNull() {
            addCriterion("q_category_child_id is not null");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdEqualTo(Short value) {
            addCriterion("q_category_child_id =", value, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdNotEqualTo(Short value) {
            addCriterion("q_category_child_id <>", value, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdGreaterThan(Short value) {
            addCriterion("q_category_child_id >", value, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdGreaterThanOrEqualTo(Short value) {
            addCriterion("q_category_child_id >=", value, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdLessThan(Short value) {
            addCriterion("q_category_child_id <", value, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdLessThanOrEqualTo(Short value) {
            addCriterion("q_category_child_id <=", value, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdIn(List<Short> values) {
            addCriterion("q_category_child_id in", values, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdNotIn(List<Short> values) {
            addCriterion("q_category_child_id not in", values, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdBetween(Short value1, Short value2) {
            addCriterion("q_category_child_id between", value1, value2, "qCategoryChildId");
            return (Criteria) this;
        }

        public Criteria andQCategoryChildIdNotBetween(Short value1, Short value2) {
            addCriterion("q_category_child_id not between", value1, value2, "qCategoryChildId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table q_manage
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}