package sample.domain.model;

public class QManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_manage.question_id
     *
     * @mbggenerated
     */
    private Short questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_manage.q_category_parent_id
     *
     * @mbggenerated
     */
    private Short qCategoryParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_manage.q_category_child_id
     *
     * @mbggenerated
     */
    private Short qCategoryChildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_manage.question
     *
     * @mbggenerated
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column q_manage.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_manage.question_id
     *
     * @return the value of q_manage.question_id
     *
     * @mbggenerated
     */
    public Short getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_manage.question_id
     *
     * @param questionId the value for q_manage.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Short questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_manage.q_category_parent_id
     *
     * @return the value of q_manage.q_category_parent_id
     *
     * @mbggenerated
     */
    public Short getqCategoryParentId() {
        return qCategoryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_manage.q_category_parent_id
     *
     * @param qCategoryParentId the value for q_manage.q_category_parent_id
     *
     * @mbggenerated
     */
    public void setqCategoryParentId(Short qCategoryParentId) {
        this.qCategoryParentId = qCategoryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_manage.q_category_child_id
     *
     * @return the value of q_manage.q_category_child_id
     *
     * @mbggenerated
     */
    public Short getqCategoryChildId() {
        return qCategoryChildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_manage.q_category_child_id
     *
     * @param qCategoryChildId the value for q_manage.q_category_child_id
     *
     * @mbggenerated
     */
    public void setqCategoryChildId(Short qCategoryChildId) {
        this.qCategoryChildId = qCategoryChildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_manage.question
     *
     * @return the value of q_manage.question
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_manage.question
     *
     * @param question the value for q_manage.question
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column q_manage.answer
     *
     * @return the value of q_manage.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column q_manage.answer
     *
     * @param answer the value for q_manage.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }
}