package sample.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import sample.domain.model.QManage;
import sample.domain.model.QManageExample;

public interface QManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    int countByExample(QManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    int deleteByExample(QManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    @Insert({
        "insert into q_manage (question_id, q_category_parent_id, ",
        "q_category_child_id, question, ",
        "answer)",
        "values (#{questionId,jdbcType=SMALLINT}, #{qCategoryParentId,jdbcType=SMALLINT}, ",
        "#{qCategoryChildId,jdbcType=SMALLINT}, #{question,jdbcType=LONGVARCHAR}, ",
        "#{answer,jdbcType=LONGVARCHAR})"
    })
    int insert(QManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    int insertSelective(QManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    List<QManage> selectByExampleWithBLOBs(QManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    List<QManage> selectByExample(QManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QManage record, @Param("example") QManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") QManage record, @Param("example") QManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table q_manage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QManage record, @Param("example") QManageExample example);
}